CREATE DATABASE SMS;

USE SMS;

CREATE TABLE Students(NAME VARCHAR(255), ADDRESS VARCHAR(255), AGE INT);

INSERT INTO Students VALUES('AKEEL','KALAWEWA',26);

SELECT* FROM Students;

CREATE TABLE PERSON(FirstName VARCHAR(255), University VARCHAR(255), Age INT, PhoneNumber INT);

INSERT INTO PERSON VALUES('Akeel', 'UCSC', 26, 0711234567);

SELECT* FROM PERSON;